---
- hosts: all
  become: true
  tasks:
    - name: stop if we have old docker container
      command: docker stop simple-devops-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm simple-devops-container
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi viswanatha/simple-devops-image:latest
      ignore_errors: yes
    #    register: result
    #    failed_when:
    #      - result.rc == 0
    #      - '"docker" not in result.stdout'


    - name: building docker image
      command: docker pull  viswanatha/simple-devops-image:latest

    - name: creating docker image
      command: docker run -d --name simple-devops-container -p 8080:8080 viswanatha/simple-devops-image:latest